#!/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
import wget

DATASET_NAME = "WaterDropSmall"
OUTPUT_DIR = f"datasets/{DATASET_NAME}"

BASE_URL = f"https://storage.googleapis.com/cs224w_course_project_dataset/{DATASET_NAME}"

META_DATA_PATH = f"{OUTPUT_DIR}/metadata.json"
CLOUD_PATH = f"{BASE_URL}/metadata.json"
wget.download(CLOUD_PATH, out=META_DATA_PATH)
for split in ["test", "train", "valid"]:
  for suffix in ["offset.json", "particle_type.dat", "position.dat"]:
      DATA_PATH = f"{OUTPUT_DIR}/{split}_{suffix}"
      CLOUD_PATH = f"{BASE_URL}/{split}_{suffix}"
      wget.download(CLOUD_PATH, out=DATA_PATH)
