# -------------- Hyperparameters for the rope system --------------

data_dir: "datasets/SpringPendulum"

# system parameters
n_bodies: 4
spring_constant: 200
gravity: -9.81
position_range: [-1.0, 1.0]
compression_range: [0.25, 1.0]

init_height: 1.0
rest_length: 0.3
radius: 0.05
mass: 1.
damping_factor: 0.025

dt: 0.02
num_train_rollouts: 50
num_valid_rollouts: 10
num_test_rollouts: 1
timesteps: 100
dim: 2
state_dim: 6  # [pos, vel, acc]
param_dim: 5

# for generating data
generate_data: false

# for training
window_length: 7
noise_std: 3e-4

video: True
