# -------------- Hyperparameters for the rope system --------------

# for generating rollouts and data
n_bodies_range: [4, 8] 
k_range: [500., 1500.]
gravity_range: [-2., -8.]
position_range: [-0.6, 0.6]

# system parameters
init_height: 1.0
rest_length: 0.3
radius: 0.06
mass: 5.
damping_factor: 0.25

dt: 0.02
n_rollout: 20
timesteps: 100
state_dim: 6
param_dim: 5
n_splits: 5

# for training
window_size: 7
noise_std: 0

video: True
