# ----------------------------------- HYPERPARAMETER CONFIG FILE -----------------------------------
defaults:  
  - _self_
  - model
  - train
  - figure
  - system: rope 
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .